// Generated by gencpp from file ex5/setDogNameResponse.msg
// DO NOT EDIT!


#ifndef EX5_MESSAGE_SETDOGNAMERESPONSE_H
#define EX5_MESSAGE_SETDOGNAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ex5
{
template <class ContainerAllocator>
struct setDogNameResponse_
{
  typedef setDogNameResponse_<ContainerAllocator> Type;

  setDogNameResponse_()
    : result(false)  {
    }
  setDogNameResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ex5::setDogNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex5::setDogNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setDogNameResponse_

typedef ::ex5::setDogNameResponse_<std::allocator<void> > setDogNameResponse;

typedef boost::shared_ptr< ::ex5::setDogNameResponse > setDogNameResponsePtr;
typedef boost::shared_ptr< ::ex5::setDogNameResponse const> setDogNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex5::setDogNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex5::setDogNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ex5::setDogNameResponse_<ContainerAllocator1> & lhs, const ::ex5::setDogNameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ex5::setDogNameResponse_<ContainerAllocator1> & lhs, const ::ex5::setDogNameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ex5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ex5::setDogNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex5::setDogNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex5::setDogNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex5::setDogNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex5::setDogNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex5::setDogNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex5::setDogNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::ex5::setDogNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ex5::setDogNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex5/setDogNameResponse";
  }

  static const char* value(const ::ex5::setDogNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex5::setDogNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::ex5::setDogNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex5::setDogNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setDogNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex5::setDogNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex5::setDogNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX5_MESSAGE_SETDOGNAMERESPONSE_H
