// Generated by gencpp from file ex5/setDogName.msg
// DO NOT EDIT!


#ifndef EX5_MESSAGE_SETDOGNAME_H
#define EX5_MESSAGE_SETDOGNAME_H

#include <ros/service_traits.h>


#include <ex5/setDogNameRequest.h>
#include <ex5/setDogNameResponse.h>


namespace ex5
{

struct setDogName
{

typedef setDogNameRequest Request;
typedef setDogNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setDogName
} // namespace ex5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex5::setDogName > {
  static const char* value()
  {
    return "ef27681b79a917a66e27f7b1af5214cd";
  }

  static const char* value(const ::ex5::setDogName&) { return value(); }
};

template<>
struct DataType< ::ex5::setDogName > {
  static const char* value()
  {
    return "ex5/setDogName";
  }

  static const char* value(const ::ex5::setDogName&) { return value(); }
};


// service_traits::MD5Sum< ::ex5::setDogNameRequest> should match
// service_traits::MD5Sum< ::ex5::setDogName >
template<>
struct MD5Sum< ::ex5::setDogNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex5::setDogName >::value();
  }
  static const char* value(const ::ex5::setDogNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex5::setDogNameRequest> should match
// service_traits::DataType< ::ex5::setDogName >
template<>
struct DataType< ::ex5::setDogNameRequest>
{
  static const char* value()
  {
    return DataType< ::ex5::setDogName >::value();
  }
  static const char* value(const ::ex5::setDogNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex5::setDogNameResponse> should match
// service_traits::MD5Sum< ::ex5::setDogName >
template<>
struct MD5Sum< ::ex5::setDogNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex5::setDogName >::value();
  }
  static const char* value(const ::ex5::setDogNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex5::setDogNameResponse> should match
// service_traits::DataType< ::ex5::setDogName >
template<>
struct DataType< ::ex5::setDogNameResponse>
{
  static const char* value()
  {
    return DataType< ::ex5::setDogName >::value();
  }
  static const char* value(const ::ex5::setDogNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX5_MESSAGE_SETDOGNAME_H
